services:
  # nginx:
  #   build:
  #     context: ./requirements/nginx
  #   ports:
  #     - "5000:8080"
  #   env_file:
  #     - .env
#     depends_on:
#       - db

  maria_db:
    build: 
      context: ./requirements/maria_db
      args:
        - DATABASE_NAME
        - DATABASE_USER
        - DATABASE_USER_PASSWORD
        - DATABASE_ROOT
        - DATABASE_ROOT_PASSWORD
    ports:
      - "3316:3306"
    env_file:
      - .env
    networks:
      - inception
    # volumes:
    #   - db_data:/var/lib/mysql

networks:
  inception:
    driver: bridge
    name: inception

# volumes:
#   db_data:
