services:
  maria_db:
    build: 
      context: ./requirements/maria_db
      args:
        - DATABASE_NAME
        - DATABASE_USER
        - DATABASE_USER_PASSWORD
        - DATABASE_ROOT
        - DATABASE_ROOT_PASSWORD
    ports:
      - "3316:3306"
    env_file:
      - .env
    networks:
      - inception
    # volumes:
    #   - db_data:/var/lib/mysql
  
  wordpress:
    build: 
      context: ./requirements/wordpress
      args:
        - DOMAIN_NAME
        - DATABASE_NAME
        - DATABASE_USER
        - DATABASE_USER_PASSWORD
        - WP_ROOT_USER
        - WP_ROOT_EMAIL
        - WP_ROOT_PASSWORD
        - WP_USER
        - WP_EMAIL
        - WP_PASSWORD
    env_file:
      - .env
    depends_on:
      - maria_db
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress

  nginx:

    build:
      context: ./requirements/nginx
    ports:
      - "8080:443"
    env_file:
      - .env
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception

networks:
  inception:
    driver: bridge
    name: inception

volumes:
  db_data:

  wordpress:
    driver: local
    driver_opts:
      device: /home/bedos-sa/wordpress
      type: none
      o: bind