name: "inception"

services:
  nginx:
    build:
      context: ./requirements/nginx
    ports:
      - "5000:8080"
#     environment:
#       - DATABASE_HOST=db
#       - DATABASE_USER=root
#       - DATABASE_PASSWORD=rootpassword
#       - DATABASE_NAME=mydb
#     depends_on:
#       - db

#   db:
#     image: mysql:8.0
#     container_name: mysql_db
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: mydb
#     volumes:
#       - db_data:/var/lib/mysql

# volumes:
#   db_data:
